### ISSUE TITLE
[enhancement]Implement the "all" option.

### ISSUE THREAD

**Issue by sig9org** [erm/mangum-cli#14]
Hi, @erm.

mangum-cli is a powerful tool and very helpful!

I want to implement the "all" option.
The "all" option performs the following successively:

1. build
2. package
3. deploy

Am I willing to implement this option?

**Comment by jordaneremieff** [comment]
I'm glad you find it helpful! If you would find this useful then I'd be happy to review your PR and merge it in.

**Comment by sig9org** [comment]
Hi, @erm.

Thank you for your reply!
mangum-cli is a great tool that can save me a lot of time. I have registered the PR #15 and would appreciate it if you could review it.
