### ISSUE TITLE
Is it possible to update PyPi?

### ISSUE THREAD

**Issue by sig9org** [erm/mangum-cli#17]
Hi, @erm.

I sent a new PR. (#16)
If you can merge the PR, will you update PyPi later?

mangum-cli
https://pypi.org/project/mangum-cli/

Regrads,

**Comment by jordaneremieff** [comment]
Sure thing, I’ll push a release after I review and merge the latest PR. Thanks.

**Comment by jordaneremieff** [comment]
Done.
