### ISSUE TITLE
Policy permission in Cloudformation template

### ISSUE THREAD

**Issue by vikahl** [erm/mangum-cli#3]
The default permissions in the cloudformation template is a bit to broad, the app gets access to all of S3 and DynamoDB which might not even be used. A finer grade permission system where only the necessary permissions would be added to only the relevant resources (i.e. only a specific S3 bucket) would provide better security for the api. 

My suggestion is to add options to the `init` function asking if S3/DynamoDB access is needed and then (optionally) add specific permissions for those resources.

I am happy to submit a PR for this change, but want to check if you have other suggestions how to handle this.

And thank you for an excellent tool, it has helped me a lot to get a FastAPI api running on AWS.

**Comment by jordaneremieff** [comment]
I'm happy to hear you are finding this project useful! I agree with your thoughts on the permissions. Please feel free to open a PR with your proposed changes, and I will take a look when I have a chance.

Thank you.
